{
 "title": "kcustomer",
 "description": "Dashboard for Micrometer(Java, Spring Boot, Actuator)",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=\"kcustomer\", }, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=\"kcustomer\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", area=\"heap\",},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", area=\"nonheap\",},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "pod",
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime $pod",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"kcustomer\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Start time $pod",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application='kcustomer', pod='$pod'}*1000",
     "legendFormat": "Uptime_{{pod}}"
    }
   ]
  },
  {
   "title": "Cpu load 10s $pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{container='kcustomer', pod='$pod'}",
     "legendFormat": "cpu_load_{{pod}}"
    }
   ]
  },
  {
   "title": " Heap used $pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\",application=\"kcustomer\",pod=\"$pod\",namespace=\"$namespace\"})/sum(jvm_memory_max_bytes{area=\"heap\",application=\"kcustomer\",pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "Heap_$pod"
    }
   ]
  },
  {
   "title": "Non-Heap used $pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\",pod=\"$pod\",namespace=\"$namespace\"})/sum(jvm_memory_max_bytes{ area=\"nonheap\",pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "Non-HeapUsage_$pod"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "pod",
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_heap $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes{application=\"kcustomer\", area=\"heap\",pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "heap_used"
    },
    {
     "expr": "sum by (pod) (jvm_memory_committed_bytes{application=\"kcustomer\", area=\"heap\",pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum by (pod) (jvm_memory_max_bytes{application=\"kcustomer\", area=\"heap\",pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod)(jvm_memory_used_bytes{application='kcustomer', area=\"nonheap\",pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum by (pod) (jvm_memory_committed_bytes{application='kcustomer', area=\"nonheap\",pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum by (pod) (jvm_memory_max_bytes{application='kcustomer', area=\"nonheap\",pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes{application='kcustomer',pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum by (pod) (jvm_memory_committed_bytes{application='kcustomer',pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum by (pod) (jvm_memory_max_bytes{application='kcustomer',pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (pod,namespace) (jvm_memory_used_bytes{application='kcustomer', area='heap'})* 100) /sum by (pod,namespace) (jvm_memory_max_bytes{application='kcustomer', area='heap'}) ",
     "legendFormat": "heap_usage_{{pod}}({{namespace}})"
    }
   ]
  },
  {
   "title": "Non Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (pod,namespace) (jvm_memory_used_bytes{application='kcustomer', area='nonheap'})* 100) /sum by (pod,namespace) (jvm_memory_max_bytes{application='kcustomer', area='nonheap'}) ",
     "legendFormat": "nonheap_usage_{{pod}}({{namespace}})"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "repeat": "pod",
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap $pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "repeat": "jvm_memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_nonheap\",pod=\"$pod\",namespace=\"$namespace\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_nonheap\",pod=\"$pod\",namespace=\"$namespace\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_nonheap\",pod=\"$pod\",namespace=\"$namespace\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Dubbo Requests Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dubbo Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (namespace,pod, interface) (increase(dubbo_request_success_total{application='kcustomer'}[2m])/120))/(sum by (namespace,pod, interface) (increase(dubbo_request_total{application='kcustomer'}[2m])/120))",
     "legendFormat": "{{pod}}_{{interface}}"
    }
   ]
  },
  {
   "title": "Dubbo Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod, interface, method) (dubbo_request_latency_seconds{application='kcustomer', quantile='0.9'}*1000)",
     "legendFormat": "{{pod}}_{{interface}}.{{method}}"
    }
   ]
  },
  {
   "title": "Dubbo Request Concurrent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "expr": "sum by (namespace,pod, interface) (increase(dubbo_request_concurrent_total{application='kcustomer'}[2m])/120)",
     "legendFormat": "{{pod}}_{{interface}}"
    }
   ]
  },
  {
   "title": "HttpRequests Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Http Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod, uri) (rate(http_server_requests_seconds_count{application='kcustomer'}[2m]))",
     "legendFormat": "HTTP_{{pod}}_{{uri}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod, uri) (rate(http_server_requests_seconds_sum{application=\"kcustomer\", status!~\"5..\"}[2m]))/sum by (namespace,pod, uri) (rate(http_server_requests_seconds_count{application=\"kcustomer\", status!~\"5..\"}[2m]))",
     "legendFormat": "HTTP - AVG-  {{ pod}}-{{uri}}"
    },
    {
     "expr": "max by (namespace,pod, uri) (http_server_requests_seconds_max{application=\"kcustomer\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX  {{ pod}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Http-Errors-5xx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod, uri) (rate(http_server_requests_seconds_count{application=\"kcustomer\", status=~\"5..\"}[2m]))",
     "legendFormat": "HTTP - 5xx- {{pod}}_{{uri}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (namespace,pod, action, cause) (rate(jvm_gc_pause_seconds_count{application=\"kcustomer\"}[2m]))",
     "legendFormat": "{{action}} ({{cause}})_{{pod}}"
    },
    {
     "expr": "avg by (namespace,pod, cause) (rate(jvm_gc_pause_seconds_count{application=\"kcustomer\", action=\"end of major GC\"}[2m]))",
     "legendFormat": "MajorGC_{{pod}}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (namespace,pod, action, cause) (rate(jvm_gc_pause_seconds_sum{application=\"kcustomer\"}[2m])/rate(jvm_gc_pause_seconds_count{application=\"kcustomer\"}[2m]))",
     "legendFormat": "avg {{action}} ({{cause}})_{{pod}}"
    },
    {
     "expr": "avg by (namespace,pod, action, cause) (jvm_gc_pause_seconds_max{application=\"kcustomer\"})",
     "legendFormat": "max {{action}} ({{cause}})_{{pod}}"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pod) (rate(jvm_gc_memory_allocated_bytes_total{application=\"kcustomer\"}[2m]))",
     "legendFormat": "Young allocated_{{pod}}"
    },
    {
     "expr": "avg by (pod) (rate(jvm_gc_memory_promoted_bytes_total{application=\"kcustomer\"}[2m]))",
     "legendFormat": "Old promoted_{{pod}}"
    }
   ]
  },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"kcustomer\"}[5m])*100)by(namespace,pod)/sum(container_spec_cpu_quota{container=\"kcustomer\"}/container_spec_cpu_period{container=\"kcustomer\"})by(namespace,pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_cpu_load_average_10s{container=\"kcustomer\"})by(namespace,pod)/1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Log Events (2m)-Error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(log4j2_events_total{application='kcustomer', level =~'error|warn'}[2m])",
     "legendFormat": "{{namespace}}_{{pod}}_{{level}}"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_states_threads{application='kcustomer'}) by (pod,namespace,state)",
     "legendFormat": "{{pod}}_{{state}}"
    },
    {
     "expr": "sum(jvm_threads_states_threads{application='kcustomer',state='blocked'}) by (pod,namespace)",
     "legendFormat": "block_thread_{{pod}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod) (jvm_threads_live_threads{application=\"kcustomer\"})",
     "legendFormat": "live_{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Restart or OOM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 98 },
   "targets": [
    {
     "expr": "sum by (container,pod,namespace) (increase(kube_pod_container_status_restarts_total{container='kcustomer'}[10m]))",
     "legendFormat": "restart_{{namespace}}_{{pod}}"
    },
    {
     "expr": "sum by (container,pod,namespace) (increase(kube_pod_container_status_last_terminated_reason{container='kcustomer', reason=\"OOMKilled\"}[10m]))",
     "legendFormat": "OOM_{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (pod) (jvm_classes_loaded_classes{application=\"kcustomer\"})",
     "legendFormat": "loaded_{{pod}}"
    }
   ]
  },
  {
   "title": "Class delta (5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (pod) (delta(jvm_classes_loaded_classes{application=\"kcustomer\"}[5m]))",
     "legendFormat": "delta_{{pod}}"
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pod) (jvm_buffer_memory_used_bytes{application=\"kcustomer\", id=\"direct\"})",
     "legendFormat": "used_{{pod}}"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"kcustomer\", id=\"direct\"}",
     "legendFormat": "capacity_{{pod}}"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{application=\"kcustomer\", id=\"direct\"}",
     "legendFormat": "count_{{pod}}"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pod) (jvm_buffer_memory_used_bytes{application=\"kcustomer\", id=\"mapped\"})",
     "legendFormat": "used_{{pod}}"
    },
    {
     "expr": "avg by (pod) (jvm_buffer_total_capacity_bytes{application=\"kcustomer\", id=\"mapped\"})",
     "legendFormat": "capacity_{{pod}}"
    }
   ]
  },
  {
   "title": "Mapped Buffers count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (pod) (jvm_buffer_count_buffers{application=\"kcustomer\", id=\"mapped\"})",
     "legendFormat": "count_{{pod}}"
    }
   ]
  }
 ]
}