{
 "title": "Ignite-Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Sys Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sys_memory_heap_used/sys_memory_heap_max) by (namespace,pod)",
     "legendFormat": "{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "Sys CpuLoad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(sys_CpuLoad) by (namespace,pod)",
     "legendFormat": "{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "Baseline nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (cluster_ActiveBaselineNodes)",
     "legendFormat": "ActiveBaselineNodes_{{job}}"
    },
    {
     "expr": "sum by (job) (cluster_TotalBaselineNodes)",
     "legendFormat": "TotalBaselineNodes_{{job}}"
    },
    {
     "expr": "sum by (job) (cluster_TotalBaselineNodes-cluster_ActiveBaselineNodes)",
     "legendFormat": "DiffBaselineNodes_{{job}}"
    },
    {
     "expr": "sum by (job) (cluster_TotalServerNodes) ",
     "legendFormat": "TotalServerNodes_{{job}}"
    }
   ]
  },
  {
   "title": "sys_ThreadCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": " avg(sys_ThreadCount) by (namespace,pod)",
     "legendFormat": "{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "sys_memory_heap(MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(sys_memory_heap_max/1000/1000/1000) by (namespace,pod)",
     "legendFormat": "heap_max_{{namespace}}_{{pod}}"
    },
    {
     "expr": "avg(sys_memory_heap_used/1000/1000) by (namespace,pod)",
     "legendFormat": "heap_used_{{namespace}}_{{pod}}"
    }
   ]
  }
 ]
}