{
 "title": "IgniteComputeJobs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "KriskJobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "krisk_compute_jobs_Active",
     "legendFormat": "jobs_Active_{{namespace}}_{{pod}}"
    },
    {
     "expr": "krisk_compute_jobs_Waiting",
     "legendFormat": "jobs_Waiting_{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "kriskJobTime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(krisk_compute_jobs_ExecutionTime[2m])",
     "legendFormat": "jobs_ExecutionTime_{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "DtmJobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "dtm_compute_jobs_Active",
     "legendFormat": "jobs_Active_{{namespace}}_{{pod}}"
    },
    {
     "expr": "dtm_compute_jobs_Waiting",
     "legendFormat": "jobs_Waiting_{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "DtmJobTime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(dtm_compute_jobs_ExecutionTime[5m])",
     "legendFormat": "jobs_ExecutionTime_{{namespace}}_{{pod}}"
    }
   ]
  }
 ]
}