{
 "title": "Ignite-DataRegionIO",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cacheDataRegion OffHeap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "io_dataregion_cacheDataRegion_OffheapUsedSize/io_dataregion_cacheDataRegion_OffHeapSize",
     "legendFormat": "cacheDataRegion_OffheapUsage_{{namespace}}_{{pod}}"
    },
    {
     "expr": "io_dataregion_cacheDataRegion_TotalAllocatedSize/io_dataregion_cacheDataRegion_MaxSize",
     "legendFormat": "cacheDataRegion_Usage_{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "Cache Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "io_dataregion_cacheDataRegion_TotalAllocatedSize/io_dataregion_cacheDataRegion_MaxSize",
     "legendFormat": "cacheDataRegionUsage_{{namespace}}_{{pod}}"
    },
    {
     "expr": "io_dataregion_sysMemPlc_TotalAllocatedSize/io_dataregion_sysMemPlc_MaxSize",
     "legendFormat": "sysMemPlcUsage_{{job}}"
    },
    {
     "expr": "io_dataregion_volatileDsMemPlc_TotalAllocatedSize/io_dataregion_volatileDsMemPlc_MaxSize",
     "legendFormat": "volatileDsMemPlc_{{namespace}}_{{pod}}"
    },
    {
     "expr": "io_dataregion_default_TotalAllocatedSize/io_dataregion_default_MaxSize",
     "legendFormat": "default__{{namespace}}_{{pod}}"
    },
    {
     "expr": "io_dataregion_TxLog_TotalAllocatedSize/io_dataregion_TxLog_MaxSize",
     "legendFormat": "TxLog__{{namespace}}_{{pod}}"
    },
    {
     "expr": "io_dataregion_metastoreMemPlc_TotalAllocatedSize/io_dataregion_metastoreMemPlc_MaxSize",
     "legendFormat": "Metastore__{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "CacheData Region OffHeapSize(MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "io_dataregion_cacheDataRegion_OffHeapSize/1000/1000",
     "legendFormat": "OffHeapSize__{{namespace}}_{{pod}}"
    },
    {
     "expr": "io_dataregion_cacheDataRegion_OffheapUsedSize/1000/1000",
     "legendFormat": "OffheapUsedSize__{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Region Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "io_dataregion_default_MaxSize", "legendFormat": "default_{{namespace}}_{{pod}}" },
    { "expr": "io_dataregion_TxLog_MaxSize", "legendFormat": "txLog_{{namespace}}_{{pod}}" },
    {
     "expr": "io_dataregion_metastoreMemPlc_MaxSize",
     "legendFormat": "metastore_{{namespace}}_{{pod}}"
    },
    {
     "expr": "io_dataregion_sysMemPlc_MaxSize",
     "legendFormat": "sysMemPlc_{{namespace}}_{{pod}}"
    },
    {
     "expr": "io_dataregion_volatileDsMemPlc_MaxSize",
     "legendFormat": "volatileDs_{{namespace}}_{{pod}}"
    }
   ]
  }
 ]
}