{
 "title": "Ignite-Storage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "StorageSize(MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "io_datastorage_StorageSize",
     "legendFormat": "StorageSize_{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "StorageWalTotalSize(MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "io_datastorage_WalTotalSize",
     "legendFormat": "WalTotalSize_{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "StorageWalWritingRate(MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "io_datastorage_WalWritingRate/1000/1000",
     "legendFormat": "{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "StorageCheckpointFsyncHistogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "io_datastorage_CheckpointFsyncHistogram_0_100",
     "legendFormat": "0_100_{{namespace}}_{{pod}}"
    },
    {
     "expr": "io_datastorage_CheckpointWalRecordFsyncHistogram_1000_5000",
     "legendFormat": "Wal_{{namespace}}_{{pod}}"
    },
    {
     "expr": "io_datastorage_CheckpointFsyncHistogram_500_1000",
     "legendFormat": "500_1000_{{namespace}}_{{pod}}"
    }
   ]
  }
 ]
}